[package]
name = "kfs"
version = "0.1.0"
authors = ["Oguzhan YAGCI <oyagci@student.42.fr>"]
edition = "2018"

[dependencies]
volatile = "0.2.3"
spin = "0.4.9"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
